services:
  - type: web
    name: social-sync-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://social-sync.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true
    plan: standard
    numInstances: 2
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 